# Tensor Basics

This is a note book that goes over the basics of creating tensors and manipulating them.

## What is a Tensor?

- A tensor is an (multi dimensional) array that obeys some transformation rules. 
- Tensors are a linear function that describes an object in a co-ordinate system (using indcies).
- When the co-ordinate system is updated (i.e another dimension is added). tensors can update themselves (they interact with the system).
- Matricies cannot interact with the system (they are just like boxes to hold numbers in). 
- Tensors can be 0 rank like scalars, 1D like arrays, 2D like Matricies or n-D (multi dimensional).
- Tensors can also contain other tensors.

https://www.geeksforgeeks.org/differences-between-a-matrix-and-a-tensor/
https://mathworld.wolfram.com/Tensor.html

*italicised text*# New section

# Creating Tensors

### Creating Tensors using tf.constant (immutable)

In [2]:
import tensorflow as tf
print('tf version',tf.__version__)

tf version 2.6.0


In [ ]:
scalar = tf.constant(7)
print('\nSCALAR\nScalar info:', scalar, '\nScalar dimensions', scalar.ndim)


SCALAR
Scalar info: tf.Tensor(7, shape=(), dtype=int32) 
Scalar dimensions 0


In [ ]:
#Create a vector
vector = tf.constant([10,10])
print('\nVECTOR\nvector info:', vector,'\nvector dimensions', vector.ndim)


VECTOR
vector info: tf.Tensor([10 10], shape=(2,), dtype=int32) 
vector dimensions 1


In [ ]:
#Create a matrix but as a float
matrix = tf.constant([[10,10],
                   [10,10]],dtype=tf.float16)
print('\nMATRIX\nMatrix info:', matrix,'\nMatrix dimensions:', matrix.ndim)


MATRIX
Matrix info: tf.Tensor(
[[10. 10.]
 [10. 10.]], shape=(2, 2), dtype=float16) 
Matrix dimensions: 2


In [ ]:
#Create a multi-dimensional tensor
tensor = tf.constant([[[3,2,4],
                      [4,5,10]],
                      [[4,50,100],
                      [300,400,400]],
                      [[400,40,8],
                       [600,700,800]]
                      ])

print('\nTensor\nTensor info:', tensor,'\nTensor dimensions:', tensor.ndim)

### Creating tensors using tf.variable (mutable)

In [ ]:
tensor_var= tf.Variable([[[3,2,4],
                      [4,5,10]],
                      [[4,50,100],
                      [300,400,400]],
                      [[400,40,8],
                       [600,700,800]]
                      ])

print('\ntensor variable info:', tensor_var)

tensor_var= tensor_var[0,0,0].assign(10)
print('\nUpdated tf variable:',tensor_var)


tensor variable info: <tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[  3,   2,   4],
        [  4,   5,  10]],

       [[  4,  50, 100],
        [300, 400, 400]],

       [[400,  40,   8],
        [600, 700, 800]]], dtype=int32)>

Updated tf variable: <tf.Variable 'UnreadVariable' shape=(3, 2, 3) dtype=int32, numpy=
array([[[ 10,   2,   4],
        [  4,   5,  10]],

       [[  4,  50, 100],
        [300, 400, 400]],

       [[400,  40,   8],
        [600, 700, 800]]], dtype=int32)>


### Creating random tensors.

This can done by setting a global random seed so that all the random tensors are the same.

~~~
tf.random.Generator.from_seed(seed=1)
~~~

Can also shuffle the order of the tensor as not to affect learning (global seed means all tensors are shuffled the same

In [ ]:
#Create random tensors from uniform distribution
ran= tf.random.Generator.from_seed(seed=1) #THis sets the global seed and makes sure that random tensors are always the same each time the programme is run.
ran= ran.normal(shape=(3,3,3))
print('random tensor:', ran)

random tensor: tf.Tensor(
[[[ 0.43842274 -0.53439844 -0.07710262]
  [ 1.5658046  -0.1012345  -0.2744976 ]
  [ 1.4204658   1.2609464  -0.43640924]]

 [[-1.9633987  -0.06452483 -1.056841  ]
  [ 1.0019137   0.6735137   0.06987712]
  [-1.4077919   1.0278524   0.27974114]]

 [[-0.01347923  1.845181    0.97061104]
  [-1.0242516  -0.6544423  -0.29738766]
  [-1.3240396   0.28785667 -0.8757901 ]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
#Shuffle order of tensor. Shuffles data so order doesn't affect learning.
#Global seed means the tensor will be shuffled the same way each
shuffle= tf.random.shuffle(ran,seed=1)
print('\nshuffled tensor:',shuffle)


shuffled tensor: tf.Tensor(
[[[ 0.43842274 -0.53439844 -0.07710262]
  [ 1.5658046  -0.1012345  -0.2744976 ]
  [ 1.4204658   1.2609464  -0.43640924]]

 [[-0.01347923  1.845181    0.97061104]
  [-1.0242516  -0.6544423  -0.29738766]
  [-1.3240396   0.28785667 -0.8757901 ]]

 [[-1.9633987  -0.06452483 -1.056841  ]
  [ 1.0019137   0.6735137   0.06987712]
  [-1.4077919   1.0278524   0.27974114]]], shape=(3, 3, 3), dtype=float32)


### Create Tensors of ones and zeros

In [ ]:
onestf=tf.ones([3,3,3])
zerostf=tf.zeros([3,3,3])

print(onestf,zerostf)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 3, 3), dtype=float32) tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


### Create Tensors from numpy

One advantage tensors have over numpy arrays is that tensors can be ran on GPU.

**Remeber** tensor shape ***must*** equal the number of elements in the original array. 

In [ ]:
import numpy as np

np_array=np.arange(1,25)
tensor_from_numpy=tf.constant(np_array,shape=(2,3,4)) #shape must equal the number of elements in original array.
print('\nTensor from numpy:',tensor_from_numpy)

# Manipulating Tensors

### Getting output from Tensors

In [3]:
tensor_ones=tf.ones([3,3,3])


In [ ]:
print('\nDatatye:', tensor_ones.dtype)
print('\nNumber of dimensions:', tensor_ones.ndim)


Datatye: <dtype: 'float32'>

Number of dimensions: 3


In [ ]:
for i in list(range(tensor_ones.ndim)):
    print(f'\nElements of tensor along {i} axis:',tensor_ones.shape[i])


Elements of tensor along 0 axis: 3

Elements of tensor along 1 axis: 3

Elements of tensor along 2 axis: 3


In [ ]:
print('\nTotal Elements of tensor:',tf.size(tensor_ones).numpy())


Total Elements of tensor: 27


### Index slicing with tensors

This is very similar to doing it with lists in python

In [10]:
print('\nGet 2nd element from tensors:', tensor_ones[:2,:2,:2])
print('\nIgnoring last dimension', tensor_ones[:2,:2,:])
print('\nLast element from tensor:',tensor_ones[:,:,-1])


Get 2nd element from tensors: tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)

Ignoring last dimension tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)

Last element from tensor: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


### Adding new axis to tensor

First method uses:

~~~
tensor[...,tf.newaxis]
~~~

The . represents an axis so similar to 
~~~
[:, :, :]
~~~

The second method uses:

~~~
tf.expand_dims(input,axis,name)
~~~

- input = tensor wanting to exapnd
- axis = on which axis (-1 means last axis)
- name = str to name tensor, optional

In [24]:
tensor_2d= tf.constant([[2,4],[2,8]])
print(tensor_2d)

tf.Tensor(
[[2 4]
 [2 8]], shape=(2, 2), dtype=int32)


In [25]:
tensor_3d=tensor_2d[...,tf.newaxis]
print(tensor_3d)

tf.Tensor(
[[[2]
  [4]]

 [[2]
  [8]]], shape=(2, 2, 1), dtype=int32)


In [30]:
tensor_3d_expand_dim = tf.expand_dims(tensor_2d,axis=-1)
print(tensor_3d_expand_dim)

tf.Tensor(
[[[2]
  [4]]

 [[2]
  [8]]], shape=(2, 2, 1), dtype=int32)
